spring.application.name=nexoreport


spring.datasource.url=jdbc:postgresql://localhost:5432/relearn_db
spring.datasource.username=postgres
spring.datasource.password=Uhirwashami54.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uhirwamelissa@gmail.com
spring.mail.password=kpzj nocx yyvo cavg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.jwt.secret=Iammelissa,andIhaveunhealthyobsessionaboutbtsmostlyv,jhopeandjimin
app.jwt.expiration-ms=86400000
app.login-url=${APP_LOGIN_URL:http://localhost:3000/login}
