spring.application.name=nexoreport


spring.datasource.url=jdbc:postgresql://nexoreport_user:eGP6CA3N5DALqczoShAGg3w1tvHdn9Xc@dpg-d7no429kh4rs73bau2u0-a/nexoreport_db
spring.datasource.username=nexoreport_user
spring.datasource.password=eGP6CA3N5DALqczoShAGg3w1tvHdn9Xc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uhirwamelissa@gmail.com
spring.mail.password=kpzj nocx yyvo cavg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.jwt.secret=Iammelissa,andIhaveunhealthyobsessionaboutbtsmostlyv,jhopeandjimin
app.jwt.expiration-ms=900000
app.auth.refresh-cookie-secure=false
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.login-url=${APP_LOGIN_URL:http://localhost:3000/login}

server.port=8080